/**
 * MAKER GOD 2.0 — Premium Plugin Maker (Safe, No Spawn)
 * File: /home/container/cmds/maker.js
 *
 * Commands:
 *  - maker start <name>         => begin creating plugin (name = filename without .js)
 *  - maker cmd <cmds>           => set command(s), e.g: "png" or "png|image|toimg"
 *  - maker desc <text>          => set description
 *  - maker type <tools|core|ai|fun|image|etc> => set plugin type
 *  - maker react <emoji>        => set reaction emoji
 *  - maker fromme <true|false>  => set fromMe / wtype
 *  - maker deps <a,b,c>         => list npm deps (just stored + shown)
 *
 *  - maker logic                => enter logic capture mode (reply lines, or send lines)
 *  - maker add                  => add replied text OR next message to logic
 *  - maker end                  => stop capture mode
 *
 *  - maker preview              => show generated plugin
 *  - maker save                 => write /cmds/<name>.js
 *  - maker cancel               => clear session
 *  - maker panic                => clear ALL sessions (emergency)
 *
 * Notes:
 *  - This does NOT use spawn/exec. No shell.
 *  - If you need to install deps, it will show: npm i ...
 */

const fs = require("fs");
const path = require("path");

const { kord, wtype } = require("../core");

// ---------- SESSION STORE ----------
const SESS = new Map(); // key => session
const TTL_MS = 20 * 60 * 1000;

function now() {
  return Date.now();
}
function key(m) {
  const chat = m?.chat || m?.key?.remoteJid || "chat";
  const sender = m?.sender || m?.key?.participant || "sender";
  return `${chat}::${sender}`;
}
function getSess(m) {
  const k = key(m);
  const s = SESS.get(k);
  if (!s) return null;
  if (s.ts && now() - s.ts > TTL_MS) {
    SESS.delete(k);
    return null;
  }
  return s;
}
function setSess(m, patch) {
  const k = key(m);
  const prev = SESS.get(k) || {};
  const next = { ...prev, ...patch, ts: now() };
  SESS.set(k, next);
  return next;
}
function clearSess(m) {
  SESS.delete(key(m));
}
function panicAll() {
  SESS.clear();
}

// ---------- TEXT HELPERS ----------
function textOf(m, arg) {
  return String(
    (typeof arg === "string" ? arg : "") ||
      m?.text ||
      m?.body ||
      m?.message?.conversation ||
      m?.message?.extendedTextMessage?.text ||
      ""
  ).trim();
}

function sanitizeName(n) {
  n = String(n || "").trim().toLowerCase();
  n = n.replace(/\.js$/i, "");
  n = n.replace(/[^a-z0-9_\-]/g, "");
  if (!n) return "";
  return n;
}

function escapeBackticks(s) {
  return String(s || "").replace(/```/g, "``\\`");
}

function safeEmoji(e) {
  e = String(e || "").trim();
  if (!e) return "";
  if (e.length > 8) return e.slice(0, 8);
  return e;
}

function parseBool(x) {
  const v = String(x || "").trim().toLowerCase();
  if (["true", "yes", "1", "on"].includes(v)) return true;
  if (["false", "no", "0", "off"].includes(v)) return false;
  return null;
}

function normalizeDeps(s) {
  const raw = String(s || "")
    .split(/[, ]+/)
    .map((x) => x.trim())
    .filter(Boolean);

  // Keep only safe package names
  const deps = raw.filter((d) => /^[a-z0-9@\/\-_\.]+$/i.test(d));
  return Array.from(new Set(deps)).slice(0, 12);
}

// ---------- GENERATOR ----------
function buildPlugin(sess) {
  const name = sess.name;
  const cmd = sess.cmd || name;
  const desc = sess.desc || "Custom plugin";
  const type = sess.type || "tools";
  const react = sess.react || "✨";
  const fromMe = sess.fromMe === false ? "false" : "wtype"; // default to wtype
  const deps = sess.deps || [];
  const logicLines = sess.logic || [];

  const header =
`/**
 * Plugin: ${name}.js
 * Generated by MAKER GOD 2.0
 * cmd: ${cmd}
 * deps: ${deps.length ? deps.join(", ") : "none"}
 */`;

  const depsComment = deps.length
    ? `// deps: ${deps.join(", ")}\n// install: npm i ${deps.join(" ")}\n`
    : `// deps: none\n`;

  const logic =
logicLines.length
  ? logicLines.join("\n")
  : `// TODO: write your logic here\nreturn m.reply("✅ ${cmd} works!");`;

  return `${header}

${depsComment}
const { kord, wtype } = require("../core");

kord(
  { cmd: "${cmd}", desc: "${escapeBackticks(desc)}", fromMe: ${fromMe}, type: "${type}", react: "${escapeBackticks(react)}" },
  async (m, arg) => {
    try {
${indent(logic, 6)}
    } catch (e) {
      return m.reply("❌ ${cmd} error: " + (e?.message || e));
    }
  }
);
`;
}

function indent(s, spaces) {
  const pad = " ".repeat(spaces);
  return String(s || "")
    .split("\n")
    .map((l) => (l.trim().length ? pad + l : ""))
    .join("\n");
}

// ---------- MAIN COMMAND ----------
kord(
  { cmd: "maker", desc: "Plugin Maker God 2.0", fromMe: wtype, type: "core", react: "🧩" },
  async (m, arg) => {
    const input = textOf(m, arg);
    const [sub, ...rest] = input.split(" ");
    const value = rest.join(" ").trim();

    if (!sub) {
      return m.reply(
        "🧩 *MAKER GOD 2.0*\n" +
          "Commands:\n" +
          "• maker start <name>\n" +
          "• maker cmd <cmd|a|b>\n" +
          "• maker desc <text>\n" +
          "• maker type <tools|core|...>\n" +
          "• maker react <emoji>\n" +
          "• maker fromme <true|false>\n" +
          "• maker deps <axios,canvas>\n" +
          "• maker logic / maker add / maker end\n" +
          "• maker preview / maker save\n" +
          "• maker cancel / maker panic"
      );
    }

    // PANIC
    if (sub === "panic") {
      panicAll();
      return m.reply("✅ Maker sessions cleared (panic).");
    }

    // START
    if (sub === "start") {
      const n = sanitizeName(value);
      if (!n) return m.reply("❌ Use: maker start <name> (letters/numbers/_/- only)");
      setSess(m, {
        name: n,
        cmd: n,
        desc: "",
        type: "tools",
        react: "✨",
        fromMe: true,
        deps: [],
        logic: [],
        capture: false,
      });

      return m.reply(
        "🧩 *Started: " + n + "*\n" +
          "Now send:\n" +
          "• maker desc <...>\n" +
          "• maker cmd <...>\n" +
          "• maker type <...>\n" +
          "• maker react <...>\n" +
          "• maker fromme <true|false>\n" +
          "• maker deps <a,b>\n\n" +
          "Then:\n" +
          "• maker logic (start capture)\n" +
          "• maker add (append replied text)\n" +
          "• maker end\n\n" +
          "Finish:\n" +
          "• maker preview\n" +
          "• maker save"
      );
    }

    const sess = getSess(m);
    if (!sess) {
      return m.reply("❌ No active maker session. Use: maker start <name>");
    }

    // SETTERS
    if (sub === "cmd") {
      const v = value || sess.name;
      setSess(m, { cmd: v });
      return m.reply("✅ cmd set: " + v);
    }

    if (sub === "desc") {
      setSess(m, { desc: value });
      return m.reply("✅ desc set.");
    }

    if (sub === "type") {
      const v = value || "tools";
      setSess(m, { type: v });
      return m.reply("✅ type set: " + v);
    }

    if (sub === "react") {
      const v = safeEmoji(value) || "✨";
      setSess(m, { react: v });
      return m.reply("✅ react set: " + v);
    }

    if (sub === "fromme") {
      const b = parseBool(value);
      if (b === null) return m.reply("❌ Use: maker fromme true OR maker fromme false");
      setSess(m, { fromMe: b });
      return m.reply("✅ fromMe set: " + b);
    }

    if (sub === "deps") {
      const deps = normalizeDeps(value);
      setSess(m, { deps });
      return m.reply(
        "✅ deps set: " + (deps.length ? deps.join(", ") : "none") +
          (deps.length ? `\n📦 Install manually: npm i ${deps.join(" ")}` : "")
      );
    }

    // LOGIC CAPTURE
    if (sub === "logic") {
      setSess(m, { capture: true });
      return m.reply("🧠 Logic capture ON.\nSend lines, or reply a message then: maker add\nStop with: maker end");
    }

    if (sub === "end") {
      setSess(m, { capture: false });
      return m.reply("✅ Logic capture OFF.");
    }

    if (sub === "add") {
      // take replied text if exists, else take current message after "maker add"
      let addText = "";
      if (m?.quoted && (m?.quoted?.text || m?.quoted?.body)) {
        addText = String(m.quoted.text || m.quoted.body || "").trim();
      } else {
        addText = value;
      }
      if (!addText) return m.reply("❌ Reply a text message OR use: maker add <line>");
      const lines = addText.split("\n").map((x) => x.replace(/\r/g, ""));
      setSess(m, { logic: [...(sess.logic || []), ...lines] });
      return m.reply("✅ Added " + lines.length + " line(s) to logic.");
    }

    // PREVIEW
    if (sub === "preview") {
      const out = buildPlugin(getSess(m));
      return m.reply("```js\n" + escapeBackticks(out).slice(0, 6500) + "\n```");
    }

    // SAVE
    if (sub === "save") {
      const out = buildPlugin(getSess(m));
      const file = path.join("/home/container/cmds", `${sess.name}.js`);
      fs.writeFileSync(file, out, "utf8");
      setSess(m, { capture: false });

      return m.reply(
        "✅ Saved plugin:\n" +
          `• File: cmds/${sess.name}.js\n` +
          `• cmd: ${sess.cmd}\n` +
          (sess.deps?.length ? `• deps: ${sess.deps.join(", ")}\n• install: npm i ${sess.deps.join(" ")}` : "• deps: none")
      );
    }

    // CANCEL
    if (sub === "cancel") {
      clearSess(m);
      return m.reply("✅ Maker session cleared.");
    }

    // default: if capture mode, treat as logic line
    if (sess.capture) {
      const line = input; // full message after "maker ..."
      // But if user typed "maker something" we shouldn't add that.
      // So if message starts with maker, ignore.
      return m.reply("⚠️ Use: maker add (or maker add <line>) while capture is ON.");
    }

    return m.reply("❌ Unknown maker command. Use: maker");
  }
);