/**
 * Plugin: png.js
 * Generated by MAKER GOD 2.0
 * cmd: png
 * deps: axios
 */

// deps: axios
// install: npm i axios

const { kord, wtype } = require("../core");

kord(
  { cmd: "png", desc: "Convert", fromMe: wtype, type: "tools", react: "🖼️" },
  async (m, arg) => {
    try {
      const axios = require("axios");
      return m.reply("PNG plugin coming soon ✅"
      return m.reply("PNG by crysnova ☠️");
    } catch (e) {
      return m.reply("❌ png error: " + (e?.message || e));
    }
  }
);